name = "inv-simple-invoice"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Browser Rendering API binding for PDF generation
# Free tier: 10 minutes/day browser time, 3 concurrent browsers
browser = { binding = "BROWSER" }
