# Cloudflare Pages configuration for SvelteKit
name = "inv-simple-invoice"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Enable Node.js compatibility for required features
[build]
command = "pnpm build"

# External dependencies that should not be bundled
[build.upload]
# Exclude Puppeteer from the build
# It won't work on Cloudflare Workers anyway
